language: go
go:
- tip
install:
- go get github.com/cihub/seelog
- go get github.com/stretchr/testify
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
before_script:
- sudo apt-get install libatk1.0-0 libc6 libasound2 libcairo2 libcap2 libcups2 libexpat1
  libexif12 libfontconfig1 libfreetype6 libglib2.0-0 libgnome-keyring0 libgtk2.0-0
  libpam0g libpango1.0-0 libpci3 libpcre3 libpixman-1-0 libpng12-0 libspeechd2 libstdc++6
  libsqlite3-0 libx11-6 libxau6 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6
  libxext6 libxfixes3 libxi6 libxinerama1 libxrandr2 libxrender1 libxtst6 zlib1g $chromeos_lib_list
  libpulse0 libbz2-1.0 libnss3-dev libgconf2-dev libudev-dev
- wget https://github.com/24hours/chrome/releases/download/v0.1.0/Release.zip
- unzip ./Release.zip
- export CGO_LDFLAGS="-L `pwd`/Release -lcef"
script: 
- go test -covermode=count -coverprofile=coverage.out -ldflags "-r ./Release"
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
env:
  global:
    secure: C8dv4BkdKwsagfw8VNEVrHIywfhp92+8SGuZlvH+/3M5yrtf7Ob4/ecMRQAcf+c+IFx7xkgOTg4yzqtbCNPkmA/vWH3PEEay7+RHC3Sg/BxuWNdat5BmDPTZXQXymPdTOLpnphgLP/8g2cs0FZaevqSxSLMU2vFnIrnQ3zLKEt0=
