//generated by: python cef_parser.py --go_file=../cef.go --c_file=../cef.c --h_file=cef.h --h_path=../ main.h -I../ 
#include "cef.h" 
#include "_cgo_export.h"

void  CEF_CALLBACK on_before_command_line_processing(struct _cef_app_t *  self, const cef_string_t *  process_type, struct _cef_command_line_t *  command_line){
	return go_OnBeforeCommandLineProcessing(self,process_type,command_line);
}
//Generate by DumpFunctionAsHandler 

void  CEF_CALLBACK on_register_custom_schemes(struct _cef_app_t *  self, struct _cef_scheme_registrar_t *  registrar){
	return go_OnRegisterCustomSchemes(self,registrar);
}
//Generate by DumpFunctionAsHandler 

struct _cef_resource_bundle_handler_t * CEF_CALLBACK get_resource_bundle_handler(struct _cef_app_t *  self){
	return go_GetResourceBundleHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_browser_process_handler_t * CEF_CALLBACK get_browser_process_handler(struct _cef_app_t *  self){
	return go_GetBrowserProcessHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_render_process_handler_t * CEF_CALLBACK get_render_process_handler(struct _cef_app_t *  self){
	return go_GetRenderProcessHandler(self);
}
//Generate by DumpFunctionAsHandler 

void initializecef_app ( cef_app_t * self){
	self->base.size = sizeof(cef_app_t);
	initialize_cef_base((cef_base_t*) self);
	self->on_before_command_line_processing = on_before_command_line_processing;
	self->on_register_custom_schemes = on_register_custom_schemes;
	self->get_resource_bundle_handler = get_resource_bundle_handler;
	self->get_browser_process_handler = get_browser_process_handler;
	self->get_render_process_handler = get_render_process_handler;
}
//Generate by DumpCInitializer 

struct _cef_context_menu_handler_t * CEF_CALLBACK get_context_menu_handler(struct _cef_client_t *  self){
	return go_GetContextMenuHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_dialog_handler_t * CEF_CALLBACK get_dialog_handler(struct _cef_client_t *  self){
	return go_GetDialogHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_display_handler_t * CEF_CALLBACK get_display_handler(struct _cef_client_t *  self){
	return go_GetDisplayHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_download_handler_t * CEF_CALLBACK get_download_handler(struct _cef_client_t *  self){
	return go_GetDownloadHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_drag_handler_t * CEF_CALLBACK get_drag_handler(struct _cef_client_t *  self){
	return go_GetDragHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_focus_handler_t * CEF_CALLBACK get_focus_handler(struct _cef_client_t *  self){
	return go_GetFocusHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_geolocation_handler_t * CEF_CALLBACK get_geolocation_handler(struct _cef_client_t *  self){
	return go_GetGeolocationHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_jsdialog_handler_t * CEF_CALLBACK get_jsdialog_handler(struct _cef_client_t *  self){
	return go_GetJsdialogHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_keyboard_handler_t * CEF_CALLBACK get_keyboard_handler(struct _cef_client_t *  self){
	return go_GetKeyboardHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_life_span_handler_t * CEF_CALLBACK get_life_span_handler(struct _cef_client_t *  self){
	return go_GetLifeSpanHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_load_handler_t * CEF_CALLBACK get_load_handler(struct _cef_client_t *  self){
	return go_GetLoadHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_render_handler_t * CEF_CALLBACK get_render_handler(struct _cef_client_t *  self){
	return go_GetRenderHandler(self);
}
//Generate by DumpFunctionAsHandler 

struct _cef_request_handler_t * CEF_CALLBACK get_request_handler(struct _cef_client_t *  self){
	return go_GetRequestHandler(self);
}
//Generate by DumpFunctionAsHandler 

int  CEF_CALLBACK on_process_message_received(struct _cef_client_t *  self, struct _cef_browser_t *  browser, cef_process_id_t  source_process, struct _cef_process_message_t *  message){
	return go_OnProcessMessageReceived(self,browser,source_process,message);
}
//Generate by DumpFunctionAsHandler 

void initializecef_client ( cef_client_t * self){
	self->base.size = sizeof(cef_client_t);
	initialize_cef_base((cef_base_t*) self);
	self->get_context_menu_handler = get_context_menu_handler;
	self->get_dialog_handler = get_dialog_handler;
	self->get_display_handler = get_display_handler;
	self->get_download_handler = get_download_handler;
	self->get_drag_handler = get_drag_handler;
	self->get_focus_handler = get_focus_handler;
	self->get_geolocation_handler = get_geolocation_handler;
	self->get_jsdialog_handler = get_jsdialog_handler;
	self->get_keyboard_handler = get_keyboard_handler;
	self->get_life_span_handler = get_life_span_handler;
	self->get_load_handler = get_load_handler;
	self->get_render_handler = get_render_handler;
	self->get_request_handler = get_request_handler;
	self->on_process_message_received = on_process_message_received;
}
//Generate by DumpCInitializer 

