//generated by: python cef_parser.py --go_file=../cef.go --c_file=../cef.c --h_file=cef.h --h_path=../ main.h -I../ 
#include "cef_base.h"
#include "include/capi/cef_app_capi.h"
#include "include/capi/cef_client_capi.h"
void initializecef_app ( cef_app_t * self);
void initializecef_client ( cef_client_t * self);
void initializecef_life_span_handler ( cef_life_span_handler_t * self);
